# Generated by Django 5.1.1 on 2024-10-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0004_signup_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_department', models.CharField(max_length=255)),
                ('company_no_of_employees', models.IntegerField()),
                ('company_weblink', models.URLField()),
                ('start_year', models.IntegerField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_branch_no', models.IntegerField()),
                ('company_certification', models.CharField(max_length=255)),
                ('company_license', models.CharField(max_length=255)),
            ],
        ),
    ]
