# Generated by Django 5.1.1 on 2024-10-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_social_media',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='company',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_branch_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
