# Generated by Django 5.1.1 on 2024-10-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0006_company_company_social_media_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='annual_income',
            new_name='annualIncome',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_branch_no',
            new_name='companyBranchNo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_certification',
            new_name='companyCertification',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_department',
            new_name='companyDepartment',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_email',
            new_name='companyEmail',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_license',
            new_name='companyLicense',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_location',
            new_name='companyLocation',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_no_of_employees',
            new_name='companyNoOfEmployees',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_phone',
            new_name='companyPhone',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_social_media',
            new_name='companySocialMedia',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_weblink',
            new_name='companyWeblink',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='net_profit',
            new_name='netProfit',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='start_year',
            new_name='startYear',
        ),
    ]
