# Generated by Django 5.1.1 on 2024-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0007_rename_annual_income_company_annualincome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=15)),
                ('company_social_media', models.JSONField(blank=True, default=list)),
                ('company_department', models.CharField(blank=True, max_length=255, null=True)),
                ('company_employees', models.IntegerField()),
                ('company_weblink', models.URLField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_branch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('company_certification', models.CharField(blank=True, max_length=100, null=True)),
                ('company_license', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
