# Generated by Django 5.1.1 on 2024-10-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0008_companydetails_delete_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyDetails',
            new_name='Company',
        ),
    ]
