# Generated by Django 5.1.1 on 2024-10-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0009_rename_companydetails_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyDetails',
        ),
    ]
