# Generated by Django 5.1.1 on 2024-10-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0010_rename_company_companydetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='company_social_media',
            new_name='company_social_media_Facebook',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='company_social_media_Instagram',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='company_social_media_Linkedin',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='company_social_media_Whatsapp_group',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
