# Generated by Django 5.1.1 on 2024-10-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0011_rename_company_social_media_companydetails_company_social_media_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='company_social_media_Twitter',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
