# Generated by Django 5.1.1 on 2024-10-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0012_companydetails_company_social_media_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_name', models.CharField(max_length=255)),
                ('hr_phone_number', models.CharField(max_length=15)),
                ('hr_email', models.EmailField(max_length=254)),
                ('hr_social_media', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_phone',
            field=models.CharField(max_length=10),
        ),
    ]
