# Generated by Django 5.1.1 on 2024-10-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0013_hrdetails_alter_companydetails_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrdetails',
            name='hr_phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hrdetails',
            name='hr_social_media',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
